import type {Unit} from "$lib/calculator/models";

export enum Units {
    PRINCIPLES_OF_COMPUTER_SCIENCE = "Principles of Computer Science",
    FUNDAMENTALS_OF_COMPUTER_SYSTEMS = "Fundamentals of Computer Systems",
    PLANNING_AND_MANAGEMENT_OF_COMPUTING_PROJECTS = "Planning and Management of Computing Projects",
    SOFTWARE_DESIGN_AND_DEVELOPMENT_PROJECT = "Software Design and Development Project",
    BUILDING_COMPUTER_SYSTEMS = "Building Computer Systems",
    IT_SYSTEMS_SECURITY = "IT Systems Security",
    IT_SYSTEMS_SECURITY_AND_ENCRYPTION = "IT Systems Security and Encryption",
    BUSINESS_APPLICATIONS_OF_SOCIAL_MEDIA = "Business Applications of Social Media",
    THE_IMPACT_OF_COMPUTING = "The Impact of Computing",
    HUMAN_COMPUTER_INTERACTION = "Human-computer Interaction",
    DIGITAL_GRAPHICS_AND_ANIMATION = "Digital Graphics and Animation",
    DIGITAL_AUDIO = "Digital Audio",
    DIGITAL_VIDEO = "Digital Video",
    COMPUTER_GAMES_DEVELOPMENT = "Computer Games Development",
    WEBSITE_DEVELOPMENT = "Website Development",
    OBJECT_ORIENTED_PROGRAMMING = "Object-oriented Programming",
    MOBILE_APPS_DEVELOPMENT = "Mobile Apps Development",
    RELATIONAL_DATABASE_DEVELOPMENT = "Relational Database Development",
    COMPUTER_NETWORKING = "Computer Networking",
    MANAGING_AND_SUPPORTING_SYSTEMS = "Managing and Supporting Systems",
    VIRTUALISATION = "Virtualisation",
    SYSTEMS_ANALYSIS_AND_DESIGN = "Systems Analysis and Design",
    SYSTEMS_METHODOLOGY = "Systems Methodology",
    EXPLORING_BUSINESS = "Exploring Business",
    DEVELOPING_A_MARKETING_CAMPAIGN = "Developing a Marketing Campaign",
    PERSONAL_AND_BUSINESS_FINANCE = "Personal and Business Finance",
    MANAGING_AN_EVENT = "Managing an Event",
    INTERNATIONAL_BUSINESS = "International Business",
    PRINCIPLES_OF_MANAGEMENT = "Principles of Management",
    BUSINESS_DECISION_MAKING = "Business Decision Making",
    RECRUITMENT_AND_SELECTION_PROCESS = "Recruitment and Selection Process",
    TEAM_BUILDING_IN_BUSINESS = "Team Building in Business",
    RECORDING_FINANCIAL_TRANSACTIONS = "Recording Financial Transactions",
    FINAL_ACCOUNTS_FOR_PUBLIC_LIMITED_COMPANIES = "Final Accounts for Public Limited Companies",
    FINANCIAL_STATEMENTS_FOR_SPECIFIC_BUSINESSES = "Financial Statements for Specific Businesses",
    COST_AND_MANAGEMENT_ACCOUNTING = "Cost and Management Accounting",
    INVESTIGATING_CUSTOMER_SERVICE = "Investigating Customer Service",
    INVESTIGATING_RETAIL_BUSINESS = "Investigating Retail Business",
    VISUAL_MERCHANDISING = "Visual Merchandising",
    DIGITAL_MARKETING = "Digital Marketing",
    CREATIVE_PROMOTION = "Creative Promotion",
    PITCHING_FOR_A_NEW_BUSINESS = "Pitching for a New Business",
    INVESTIGATING_CORPORATE_SOCIAL_RESPONSIBILITY = "Investigating Corporate Social Responsibility",
    TRAINING_AND_DEVELOPMENT = "Training and Development",
    MARKET_RESEARCH = "Market Research",
    THE_ENGLISH_LEGAL_SYSTEM = "The English Legal System",
    EMPLOYMENT_LAW = "Employment Law",
    ASPECTS_OF_CIVIL_LIABILITY_AFFECTING_BUSINESS = "Aspects of Civil Liability Affecting Business",
    ASPECTS_OF_CRIMINAL_LAW_IMPACTING_ON_BUSINESS_AND_INDIVIDUALS = "Aspects of Criminal Law Impacting on Business and Individuals",
    WORK_EXPERIENCE_IN_BUSINESS = "Work Experience in Business",
    BRANDING = "Branding",
    RELATIONSHIP_MARKETING = "Relationship Marketing",
    LEGAL_PRINCIPLES_AND_PROFESSIONAL_ETHICS_IN_FINANCIAL_SERVICES = "Legal Principles and Professional Ethics in Financial Services",
    EFFECTIVE_MANAGEMENT_OF_PERSONAL_DEBT = "Effective Management of Personal Debt",
    BUYING_FOR_BUSINESS = "Buying for Business",
    SUPPLY_CHAIN_OPERATIONS = "Supply Chain Operations",
    INVESTMENT_OPPORTUNITIES_AND_FINANCIAL_PLANNING = "Investment Opportunities and Financial Planning",
    INSURANCE_PRINCIPLES_AND_POLICIES = "Insurance Principles and Policies",
    GENERIC_OPTIONAL_UNIT = "GENERIC_OPTIONAL_UNIT"
}

export const UnitDetails: Record<Units, Unit> = {
    [Units.PRINCIPLES_OF_COMPUTER_SCIENCE]: { name: Units.PRINCIPLES_OF_COMPUTER_SCIENCE, guidedLearningHours: 120 },
    [Units.FUNDAMENTALS_OF_COMPUTER_SYSTEMS]: { name: Units.FUNDAMENTALS_OF_COMPUTER_SYSTEMS, guidedLearningHours: 90 },
    [Units.PLANNING_AND_MANAGEMENT_OF_COMPUTING_PROJECTS]: { name: Units.PLANNING_AND_MANAGEMENT_OF_COMPUTING_PROJECTS, guidedLearningHours: 120 },
    [Units.SOFTWARE_DESIGN_AND_DEVELOPMENT_PROJECT]: { name: Units.SOFTWARE_DESIGN_AND_DEVELOPMENT_PROJECT, guidedLearningHours: 120 },
    [Units.BUILDING_COMPUTER_SYSTEMS]: { name: Units.BUILDING_COMPUTER_SYSTEMS, guidedLearningHours: 60 },
    [Units.IT_SYSTEMS_SECURITY]: { name: Units.IT_SYSTEMS_SECURITY, guidedLearningHours: 60 },
    [Units.IT_SYSTEMS_SECURITY_AND_ENCRYPTION]: { name: Units.IT_SYSTEMS_SECURITY_AND_ENCRYPTION, guidedLearningHours: 90 },
    [Units.BUSINESS_APPLICATIONS_OF_SOCIAL_MEDIA]: { name: Units.BUSINESS_APPLICATIONS_OF_SOCIAL_MEDIA, guidedLearningHours: 90 },
    [Units.THE_IMPACT_OF_COMPUTING]: { name: Units.THE_IMPACT_OF_COMPUTING, guidedLearningHours: 90 },
    [Units.HUMAN_COMPUTER_INTERACTION]: { name: Units.HUMAN_COMPUTER_INTERACTION, guidedLearningHours: 60 },
    [Units.DIGITAL_GRAPHICS_AND_ANIMATION]: { name: Units.DIGITAL_GRAPHICS_AND_ANIMATION, guidedLearningHours: 60 },
    [Units.DIGITAL_AUDIO]: { name: Units.DIGITAL_AUDIO, guidedLearningHours: 60 },
    [Units.DIGITAL_VIDEO]: { name: Units.DIGITAL_VIDEO, guidedLearningHours: 60 },
    [Units.COMPUTER_GAMES_DEVELOPMENT]: { name: Units.COMPUTER_GAMES_DEVELOPMENT, guidedLearningHours: 60 },
    [Units.WEBSITE_DEVELOPMENT]: { name: Units.WEBSITE_DEVELOPMENT, guidedLearningHours: 60 },
    [Units.OBJECT_ORIENTED_PROGRAMMING]: { name: Units.OBJECT_ORIENTED_PROGRAMMING, guidedLearningHours: 60 },
    [Units.MOBILE_APPS_DEVELOPMENT]: { name: Units.MOBILE_APPS_DEVELOPMENT, guidedLearningHours: 60 },
    [Units.RELATIONAL_DATABASE_DEVELOPMENT]: { name: Units.RELATIONAL_DATABASE_DEVELOPMENT, guidedLearningHours: 60 },
    [Units.COMPUTER_NETWORKING]: { name: Units.COMPUTER_NETWORKING, guidedLearningHours: 60 },
    [Units.MANAGING_AND_SUPPORTING_SYSTEMS]: { name: Units.MANAGING_AND_SUPPORTING_SYSTEMS, guidedLearningHours: 60 },
    [Units.VIRTUALISATION]: { name: Units.VIRTUALISATION, guidedLearningHours: 60 },
    [Units.SYSTEMS_ANALYSIS_AND_DESIGN]: { name: Units.SYSTEMS_ANALYSIS_AND_DESIGN, guidedLearningHours: 60 },
    [Units.SYSTEMS_METHODOLOGY]: { name: Units.SYSTEMS_METHODOLOGY, guidedLearningHours: 60 },
    [Units.EXPLORING_BUSINESS]: { name: Units.EXPLORING_BUSINESS, guidedLearningHours: 90 },
    [Units.DEVELOPING_A_MARKETING_CAMPAIGN]: { name: Units.DEVELOPING_A_MARKETING_CAMPAIGN, guidedLearningHours: 90 },
    [Units.PERSONAL_AND_BUSINESS_FINANCE]: { name: Units.PERSONAL_AND_BUSINESS_FINANCE, guidedLearningHours: 120 },
    [Units.MANAGING_AN_EVENT]: { name: Units.MANAGING_AN_EVENT, guidedLearningHours: 90 },
    [Units.INTERNATIONAL_BUSINESS]: { name: Units.INTERNATIONAL_BUSINESS, guidedLearningHours: 90 },
    [Units.PRINCIPLES_OF_MANAGEMENT]: { name: Units.PRINCIPLES_OF_MANAGEMENT, guidedLearningHours: 120 },
    [Units.BUSINESS_DECISION_MAKING]: { name: Units.BUSINESS_DECISION_MAKING, guidedLearningHours: 120 },
    [Units.RECRUITMENT_AND_SELECTION_PROCESS]: { name: Units.RECRUITMENT_AND_SELECTION_PROCESS, guidedLearningHours: 60 },
    [Units.TEAM_BUILDING_IN_BUSINESS]: { name: Units.TEAM_BUILDING_IN_BUSINESS, guidedLearningHours: 60 },
    [Units.RECORDING_FINANCIAL_TRANSACTIONS]: { name: Units.RECORDING_FINANCIAL_TRANSACTIONS, guidedLearningHours: 60 },
    [Units.FINAL_ACCOUNTS_FOR_PUBLIC_LIMITED_COMPANIES]: { name: Units.FINAL_ACCOUNTS_FOR_PUBLIC_LIMITED_COMPANIES, guidedLearningHours: 60 },
    [Units.FINANCIAL_STATEMENTS_FOR_SPECIFIC_BUSINESSES]: { name: Units.FINANCIAL_STATEMENTS_FOR_SPECIFIC_BUSINESSES, guidedLearningHours: 60 },
    [Units.COST_AND_MANAGEMENT_ACCOUNTING]: { name: Units.COST_AND_MANAGEMENT_ACCOUNTING, guidedLearningHours: 60 },
    [Units.INVESTIGATING_CUSTOMER_SERVICE]: { name: Units.INVESTIGATING_CUSTOMER_SERVICE, guidedLearningHours: 60 },
    [Units.INVESTIGATING_RETAIL_BUSINESS]: { name: Units.INVESTIGATING_RETAIL_BUSINESS, guidedLearningHours: 60 },
    [Units.VISUAL_MERCHANDISING]: { name: Units.VISUAL_MERCHANDISING, guidedLearningHours: 60 },
    [Units.DIGITAL_MARKETING]: { name: Units.DIGITAL_MARKETING, guidedLearningHours: 60 },
    [Units.CREATIVE_PROMOTION]: { name: Units.CREATIVE_PROMOTION, guidedLearningHours: 60 },
    [Units.PITCHING_FOR_A_NEW_BUSINESS]: { name: Units.PITCHING_FOR_A_NEW_BUSINESS, guidedLearningHours: 60 },
    [Units.INVESTIGATING_CORPORATE_SOCIAL_RESPONSIBILITY]: { name: Units.INVESTIGATING_CORPORATE_SOCIAL_RESPONSIBILITY, guidedLearningHours: 60 },
    [Units.TRAINING_AND_DEVELOPMENT]: { name: Units.TRAINING_AND_DEVELOPMENT, guidedLearningHours: 60 },
    [Units.MARKET_RESEARCH]: { name: Units.MARKET_RESEARCH, guidedLearningHours: 60 },
    [Units.THE_ENGLISH_LEGAL_SYSTEM]: { name: Units.THE_ENGLISH_LEGAL_SYSTEM, guidedLearningHours: 60 },
    [Units.EMPLOYMENT_LAW]: { name: Units.EMPLOYMENT_LAW, guidedLearningHours: 60 },
    [Units.ASPECTS_OF_CIVIL_LIABILITY_AFFECTING_BUSINESS]: { name: Units.ASPECTS_OF_CIVIL_LIABILITY_AFFECTING_BUSINESS, guidedLearningHours: 60 },
    [Units.ASPECTS_OF_CRIMINAL_LAW_IMPACTING_ON_BUSINESS_AND_INDIVIDUALS]: { name: Units.ASPECTS_OF_CRIMINAL_LAW_IMPACTING_ON_BUSINESS_AND_INDIVIDUALS, guidedLearningHours: 60 },
    [Units.WORK_EXPERIENCE_IN_BUSINESS]: { name: Units.WORK_EXPERIENCE_IN_BUSINESS, guidedLearningHours: 60 },
    [Units.BRANDING]: { name: Units.BRANDING, guidedLearningHours: 60 },
    [Units.RELATIONSHIP_MARKETING]: { name: Units.RELATIONSHIP_MARKETING, guidedLearningHours: 60 },
    [Units.LEGAL_PRINCIPLES_AND_PROFESSIONAL_ETHICS_IN_FINANCIAL_SERVICES]: { name: Units.LEGAL_PRINCIPLES_AND_PROFESSIONAL_ETHICS_IN_FINANCIAL_SERVICES, guidedLearningHours: 60 },
    [Units.EFFECTIVE_MANAGEMENT_OF_PERSONAL_DEBT]: { name: Units.EFFECTIVE_MANAGEMENT_OF_PERSONAL_DEBT, guidedLearningHours: 60 },
    [Units.BUYING_FOR_BUSINESS]: { name: Units.BUYING_FOR_BUSINESS, guidedLearningHours: 60 },
    [Units.SUPPLY_CHAIN_OPERATIONS]: { name: Units.SUPPLY_CHAIN_OPERATIONS, guidedLearningHours: 60 },
    [Units.INVESTMENT_OPPORTUNITIES_AND_FINANCIAL_PLANNING]: { name: Units.INVESTMENT_OPPORTUNITIES_AND_FINANCIAL_PLANNING, guidedLearningHours: 60 },
    [Units.INSURANCE_PRINCIPLES_AND_POLICIES]: { name: Units.INSURANCE_PRINCIPLES_AND_POLICIES, guidedLearningHours: 60 },
    [Units.GENERIC_OPTIONAL_UNIT]: { name: Units.GENERIC_OPTIONAL_UNIT, guidedLearningHours: 60 }
};

export function getGuidedLearningHoursByUnitName(unitName: string): number {
    return Object.values(UnitDetails).find(unit => unit.name === unitName)!.guidedLearningHours;

}
